Algoritmo "Entrada de dados e saida"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2021
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   leia (nome)
   leia (nota)

Fimalgoritmo